#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# and print "Hello World"
#

apt update
apt install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx restart
