#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# and print "Hello World"


sudo apt-get update
sudo apt-get install nginx
sudo ufw 'Nginx HTTP'

echo 'Hello World!' | sudo tee /var/www/html/index.html

# testing nginx configuration
sudo nginx -t

sudo service nginx reload
