#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# and print "Hello World"

sudo apt-get -y update
sudo apt-get -y install nginx

ufw allow 'Nginx HTTP'
sudo sed -i 's/80 default_server/80/' /etc/nginx/sites-available/default
sudo service nginx restart

echo 'Hello World!' | sudo tee /var/www/html/index.html > /dev/null
