#!/usr/bin/env bash
# bash: script installs and configures Nginx web server
# and redirects traffic:

sudo apt-get update -y
sudo apt-get install -y nginx

# configuring Nginx
sudo sed -i 's/80 default_server/80/' /etc/nginx/sites-available/default

# creating index.html file served out by server:
# & configuring the redirection
echo 'Hello World!' > /etc/nginx/html/index.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://stackoverflow.com/;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
